### PR TITLE
Cleanup and fixes

### PR DESCRIPTION
**Pull request by ghost**
This pull request replaces a few methods used in the code. I used IntelliJ to find these issues, but I haven't tested the fixes it suggested yet. Each fix suggest by intellij was made individually to make it easier to read through.

Feel free to review and cherry pick certain commits as needed.

### CODE REVIEW

**Comment by Savestate2A03** [comment]
I used to be worried about string concatenation efficiency, but considering that it's only run once when I do it with StringBuilder, the readability trade-off is probably worth it. A lot of this stuff is good, and really shows the bad decisions I made a long time ago haha. I'm gonna look over it one more time tomorrow before merging. 

Thanks for the cleanup!

**Comment by ghost** [comment]
[inspections.zip](https://github.com/Savestate2A03/FTM2GBMC/files/1765599/inspections.zip)

Here's the remaining issues pointed out by IntelliJ. It looks like it can refactor the lines that have duplicated code, but I need a name for each one of the 14 before I can do so.

I'm pretty sure these inspections are available on the Community edition of IntelliJ, but since I'm using the education version of it it might have a little more so.

**Comment by Savestate2A03** [comment]
Ah! Great, I'll check out the inspections tomorrow and let you know.

**Comment by Savestate2A03** [comment]
Haven't gotten around to checking the inspections still, but it's on the to-do. 
Thanks for the cleanup you've already done though !

**Pull request merged**
